server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://db.watent.net:3306/test-order-db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: mq.watent.net
    port: 5672
    username: admin
    password: 12345678
    publisher-confirms: true
logging:
  level:
    root: warn