# XA/JTA 事务数据源
spring:
  jta:
    atomikos:
      datasource:
        order-datasource:
          xa-properties:
            url: jdbc:mysql://db.watent.net:3306/test-order-db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
            user: tony
            password: tony
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
        dispatch-datasource:
          xa-properties:
            url: jdbc:mysql://db.watent.net:3306/test-dispatch-db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
            user: tony
            password: tony
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource

# 普通多数据源
#mall:
#  order-datasource:
#    jdbc-url: jdbc:mysql://db.watent.net:3306/test-order-db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: tony
#    password: tony
#    driver-class-name: com.mysql.jdbc.Driver
#  dispatch-datasource:
#    jdbc-url: jdbc:mysql://db.watent.net:3306/test-dispatch-db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: tony
#    password: tony
#    driver-class-name: com.mysql.jdbc.Driver
